#!/bin/zsh

###############################################################################
# Accessibility
###############################################################################

# Use scroll gesture with the Ctrl (^) modifier key to zoom.
defaults write com.apple.universalaccess closeViewScrollWheelToggle -bool true
defaults write com.apple.universalaccess HIDScrollZoomModifierMask -int 262144

###############################################################################
# Dock
###############################################################################

# Automatically hide and show the Dock.
defaults write com.apple.dock autohide -bool true

###############################################################################
# Finder
###############################################################################

# Always open everything in list view.
defaults write com.apple.Finder FXPreferredViewStyle Nlsv

# Avoid creating .DS_Store files on network volumes.
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

# Disable the warning when changing a file extension.
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Make Dock icons of hidden applications translucent.
defaults write com.apple.dock showhidden -bool true

# New finder window shows your home folder.
defaults write com.apple.finder NewWindowTarget PfHm

# Show all filename extensions.
defaults write -g  AppleShowAllExtensions -bool true

# Show icons for hard drives, servers, and removable media on the desktop.
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

# Show the ~/Library folder.
chflags nohidden ~/Library

# When performing a search, search the current folder by default.
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

###############################################################################
# Hot Corners
###############################################################################

# Bottom left screen corner → Start screen saver.
defaults write com.apple.dock wvous-br-corner -int 5
defaults write com.apple.dock wvous-br-modifier -int 0

# Top left screen corner → Mission Control.
defaults write com.apple.dock wvous-tl-corner -int 2
defaults write com.apple.dock wvous-tl-modifier -int 0

# Top right screen corner → Desktop.
defaults write com.apple.dock wvous-tr-corner -int 4
defaults write com.apple.dock wvous-tr-modifier -int 0

###############################################################################
# Keyboard
###############################################################################

# Disable press-and-hold for keys in favor of key repeat.
defaults write -g ApplePressAndHoldEnabled -bool false

# Enable full keyboard access for all controls.
defaults write -g AppleKeyboardUIMode -int 3

# Set a really fast key repeat.
defaults write -g KeyRepeat -int 1

# Set a shorter delay until key repeat.
defaults write -g InitialKeyRepeat -int 12

###############################################################################
# Keyboard Shortcuts
###############################################################################

# Add the keyboard shortcut ⌘⌥↑ to select previous conversation.
defaults write -app Messages NSUserKeyEquivalents -dict-add "Select Previous Conversation" "@~↑"

# Add the keyboard shortcut ⌘⌥↓ to select next conversation.
defaults write -app Messages NSUserKeyEquivalents -dict-add "Select Next Conversation" "@~↓"

# Add the keyboard shortcut ⌘⌥→ to select next tab.
defaults write -g NSUserKeyEquivalents -dict-add "Select Next Tab" -string "@~→"

# Add the keyboard shortcut ⌘⌥← to select previous tab.
defaults write -g NSUserKeyEquivalents -dict-add "Select Previous Tab" -string "@~←"

# Add the keyboard shortcut ⌘⌥→ to show next tab.
defaults write -g NSUserKeyEquivalents -dict-add "Show Next Tab" -string "@~→"

# Add the keyboard shortcut ⌘⌥← to show previous tab.
defaults write -g NSUserKeyEquivalents -dict-add "Show Previous Tab" -string "@~←"

# Add the keyboard shortcut ⌘^F to enter full screen.
defaults write -g NSUserKeyEquivalents -dict-add "Enter Full Screen" -string "@^f"

# Add the keyboard shortcut ⌘^F to exit full screen.
defaults write -g NSUserKeyEquivalents -dict-add "Exit Full Screen" -string "@^f"

###############################################################################
# Menu bar
###############################################################################

# Show battery percentage.
defaults write com.apple.menuextra.battery ShowPercent -string "YES"

###############################################################################
# Safari
###############################################################################

# Disable opening ‘safe’ files automatically after downloading.
defaults write com.apple.Safari AutoOpenSafeDownloads -bool false

###############################################################################
# Spotlight
###############################################################################

# Disable indexing for any volume that gets mounted and has not yet (requires sudo).
sudo defaults write /.Spotlight-V100/VolumeConfiguration Exclusions -array "/Volumes"

###############################################################################
# System
###############################################################################

# Expand print panel by default.
defaults write -g PMPrintingExpandedStateForPrint -bool true
defaults write -g PMPrintingExpandedStateForPrint2 -bool true

# Expand save panel by default.
defaults write -g NSNavPanelExpandedStateForSaveMode -bool true
defaults write -g NSNavPanelExpandedStateForSaveMode2 -bool true

# Set dark mode.
osascript -e 'tell application "System Events" to tell appearance preferences to set dark mode to not dark mode'
