#!/bin/bash

# Enable Session Restoration.
defaults write com.googlecode.iterm2 KillJobsInServersOnQuit -bool false
defaults write com.googlecode.iterm2 OnlyWhenMoreTabs -bool false
defaults write com.googlecode.iterm2 PromptOnQuit -bool false

# Add "Snazzy" color theme from sindresorhus/iterm2-snazzy.
THEME=$(curl -sSL 'https://github.com/sindresorhus/iterm2-snazzy/raw/master/Snazzy.itermcolors')

plutil -replace "Custom Color Presets" -json "{}" ~/Library/Preferences/com.googlecode.iterm2.plist
plutil -insert "Custom Color Presets.Snazzy" -xml "$THEME" ~/Library/Preferences/com.googlecode.iterm2.plist
